Version: 2.1

jobs:
  build:
    docker:
      - image: 'gcc:latest'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: apt-get update && apt-get install -y cmake && cmake . && make
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud