version: 2.1

jobs:
  build:
    docker:
      - image: 'gcc:latest'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: |
            apt-get update && apt-get install -y cmake && cmake .
      - run:
          name: Install build-wrapper
          command: |
            curl -L -o build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
            unzip build-wrapper-linux-x86.zip
      - run:
          name: Build with build-wrapper
          command: |
            mkdir -p bw-output ./build-wrapper-linux-x86-64/build-wrapper-linux-x86-64 --out-dir bw-output make
      - run:
          name: Run SonarCloud analysis
          command: sonar-scanner -Dsonar.projectKey=PhilippSchlehuberCaissier_sonartest -Dsonar.organization=philippschlehubercaissier -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output


orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
